// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/recall/config/v1/config.proto

package configv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecallConfig is the operator-owned provider registry loaded by recall.
type RecallConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Providers available to recall. Disabled providers remain configured but are
	// skipped during query fan-out.
	Providers     []*Provider `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallConfig) Reset() {
	*x = RecallConfig{}
	mi := &file_proto_recall_config_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallConfig) ProtoMessage() {}

func (x *RecallConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_config_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallConfig.ProtoReflect.Descriptor instead.
func (*RecallConfig) Descriptor() ([]byte, []int) {
	return file_proto_recall_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *RecallConfig) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

// Provider declares one searchable source and how recall can reach it. The
// SearchProvider service and method path are protocol concerns, not
// operator-owned config fields.
type Provider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operator-facing provider identifier used for routing, rendering, and
	// diagnostics.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Whether recall should include this provider in normal query fan-out.
	Enabled bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Exactly one transport must be configured.
	//
	// Types that are valid to be assigned to Transport:
	//
	//	*Provider_Stdio
	//	*Provider_Grpc
	Transport isProvider_Transport `protobuf_oneof:"transport"`
	// Cross-provider ranking weight. Must be positive.
	Weight float64 `protobuf:"fixed64,20,opt,name=weight,proto3" json:"weight,omitempty"`
	// Provider call timeout in milliseconds. Must be positive.
	TimeoutMs uint32 `protobuf:"varint,21,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// Default per-provider result limit. Must be positive.
	DefaultLimit  uint32 `protobuf:"varint,22,opt,name=default_limit,json=defaultLimit,proto3" json:"default_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_proto_recall_config_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_config_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_proto_recall_config_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *Provider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Provider) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Provider) GetTransport() isProvider_Transport {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *Provider) GetStdio() *StdioTransport {
	if x != nil {
		if x, ok := x.Transport.(*Provider_Stdio); ok {
			return x.Stdio
		}
	}
	return nil
}

func (x *Provider) GetGrpc() *GrpcTransport {
	if x != nil {
		if x, ok := x.Transport.(*Provider_Grpc); ok {
			return x.Grpc
		}
	}
	return nil
}

func (x *Provider) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Provider) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Provider) GetDefaultLimit() uint32 {
	if x != nil {
		return x.DefaultLimit
	}
	return 0
}

type isProvider_Transport interface {
	isProvider_Transport()
}

type Provider_Stdio struct {
	Stdio *StdioTransport `protobuf:"bytes,10,opt,name=stdio,proto3,oneof"`
}

type Provider_Grpc struct {
	Grpc *GrpcTransport `protobuf:"bytes,11,opt,name=grpc,proto3,oneof"`
}

func (*Provider_Stdio) isProvider_Transport() {}

func (*Provider_Grpc) isProvider_Transport() {}

// StdioTransport starts a provider process for one unary RPC call over stdin
// and stdout.
type StdioTransport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Executable path or command name to start.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Static command arguments supplied after command.
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// Additional environment variables supplied to the provider process.
	Env           map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdioTransport) Reset() {
	*x = StdioTransport{}
	mi := &file_proto_recall_config_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdioTransport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdioTransport) ProtoMessage() {}

func (x *StdioTransport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_config_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdioTransport.ProtoReflect.Descriptor instead.
func (*StdioTransport) Descriptor() ([]byte, []int) {
	return file_proto_recall_config_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *StdioTransport) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StdioTransport) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *StdioTransport) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// GrpcTransport connects to a provider that exposes the recall search service
// over gRPC.
type GrpcTransport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gRPC endpoint, for example dns:///mail-search.internal:443.
	Endpoint      string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcTransport) Reset() {
	*x = GrpcTransport{}
	mi := &file_proto_recall_config_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcTransport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcTransport) ProtoMessage() {}

func (x *GrpcTransport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_config_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcTransport.ProtoReflect.Descriptor instead.
func (*GrpcTransport) Descriptor() ([]byte, []int) {
	return file_proto_recall_config_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *GrpcTransport) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

var File_proto_recall_config_v1_config_proto protoreflect.FileDescriptor

const file_proto_recall_config_v1_config_proto_rawDesc = "" +
	"\n" +
	"#proto/recall/config/v1/config.proto\x12\x10recall.config.v1\"H\n" +
	"\fRecallConfig\x128\n" +
	"\tproviders\x18\x01 \x03(\v2\x1a.recall.config.v1.ProviderR\tproviders\"\x8e\x02\n" +
	"\bProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x128\n" +
	"\x05stdio\x18\n" +
	" \x01(\v2 .recall.config.v1.StdioTransportH\x00R\x05stdio\x125\n" +
	"\x04grpc\x18\v \x01(\v2\x1f.recall.config.v1.GrpcTransportH\x00R\x04grpc\x12\x16\n" +
	"\x06weight\x18\x14 \x01(\x01R\x06weight\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x15 \x01(\rR\ttimeoutMs\x12#\n" +
	"\rdefault_limit\x18\x16 \x01(\rR\fdefaultLimitB\v\n" +
	"\ttransport\"\xb3\x01\n" +
	"\x0eStdioTransport\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12;\n" +
	"\x03env\x18\x03 \x03(\v2).recall.config.v1.StdioTransport.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\rGrpcTransport\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpointB;Z9github.com/solodov/recall/proto/recall/config/v1;configv1b\x06proto3"

var (
	file_proto_recall_config_v1_config_proto_rawDescOnce sync.Once
	file_proto_recall_config_v1_config_proto_rawDescData []byte
)

func file_proto_recall_config_v1_config_proto_rawDescGZIP() []byte {
	file_proto_recall_config_v1_config_proto_rawDescOnce.Do(func() {
		file_proto_recall_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recall_config_v1_config_proto_rawDesc), len(file_proto_recall_config_v1_config_proto_rawDesc)))
	})
	return file_proto_recall_config_v1_config_proto_rawDescData
}

var file_proto_recall_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_recall_config_v1_config_proto_goTypes = []any{
	(*RecallConfig)(nil),   // 0: recall.config.v1.RecallConfig
	(*Provider)(nil),       // 1: recall.config.v1.Provider
	(*StdioTransport)(nil), // 2: recall.config.v1.StdioTransport
	(*GrpcTransport)(nil),  // 3: recall.config.v1.GrpcTransport
	nil,                    // 4: recall.config.v1.StdioTransport.EnvEntry
}
var file_proto_recall_config_v1_config_proto_depIdxs = []int32{
	1, // 0: recall.config.v1.RecallConfig.providers:type_name -> recall.config.v1.Provider
	2, // 1: recall.config.v1.Provider.stdio:type_name -> recall.config.v1.StdioTransport
	3, // 2: recall.config.v1.Provider.grpc:type_name -> recall.config.v1.GrpcTransport
	4, // 3: recall.config.v1.StdioTransport.env:type_name -> recall.config.v1.StdioTransport.EnvEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_recall_config_v1_config_proto_init() }
func file_proto_recall_config_v1_config_proto_init() {
	if File_proto_recall_config_v1_config_proto != nil {
		return
	}
	file_proto_recall_config_v1_config_proto_msgTypes[1].OneofWrappers = []any{
		(*Provider_Stdio)(nil),
		(*Provider_Grpc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recall_config_v1_config_proto_rawDesc), len(file_proto_recall_config_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_recall_config_v1_config_proto_goTypes,
		DependencyIndexes: file_proto_recall_config_v1_config_proto_depIdxs,
		MessageInfos:      file_proto_recall_config_v1_config_proto_msgTypes,
	}.Build()
	File_proto_recall_config_v1_config_proto = out.File
	file_proto_recall_config_v1_config_proto_goTypes = nil
	file_proto_recall_config_v1_config_proto_depIdxs = nil
}
