// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/recall/rpc/v1/rpc.proto

package rpcv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PayloadEncoding identifies the protobuf payload encoding used for a unary
// stdio RPC call.
type PayloadEncoding int32

const (
	PayloadEncoding_PAYLOAD_ENCODING_UNSPECIFIED        PayloadEncoding = 0
	PayloadEncoding_PAYLOAD_ENCODING_PROTOBUF_BINARY    PayloadEncoding = 1
	PayloadEncoding_PAYLOAD_ENCODING_PROTOBUF_TEXTPROTO PayloadEncoding = 2
)

// Enum value maps for PayloadEncoding.
var (
	PayloadEncoding_name = map[int32]string{
		0: "PAYLOAD_ENCODING_UNSPECIFIED",
		1: "PAYLOAD_ENCODING_PROTOBUF_BINARY",
		2: "PAYLOAD_ENCODING_PROTOBUF_TEXTPROTO",
	}
	PayloadEncoding_value = map[string]int32{
		"PAYLOAD_ENCODING_UNSPECIFIED":        0,
		"PAYLOAD_ENCODING_PROTOBUF_BINARY":    1,
		"PAYLOAD_ENCODING_PROTOBUF_TEXTPROTO": 2,
	}
)

func (x PayloadEncoding) Enum() *PayloadEncoding {
	p := new(PayloadEncoding)
	*p = x
	return p
}

func (x PayloadEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_recall_rpc_v1_rpc_proto_enumTypes[0].Descriptor()
}

func (PayloadEncoding) Type() protoreflect.EnumType {
	return &file_proto_recall_rpc_v1_rpc_proto_enumTypes[0]
}

func (x PayloadEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadEncoding.Descriptor instead.
func (PayloadEncoding) EnumDescriptor() ([]byte, []int) {
	return file_proto_recall_rpc_v1_rpc_proto_rawDescGZIP(), []int{0}
}

// StdioRpcCapabilitiesRequest carries no fields because capabilities are tied
// to the provider binary and invocation environment.
type StdioRpcCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdioRpcCapabilitiesRequest) Reset() {
	*x = StdioRpcCapabilitiesRequest{}
	mi := &file_proto_recall_rpc_v1_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdioRpcCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdioRpcCapabilitiesRequest) ProtoMessage() {}

func (x *StdioRpcCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_rpc_v1_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdioRpcCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*StdioRpcCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_recall_rpc_v1_rpc_proto_rawDescGZIP(), []int{0}
}

// StdioRpcCapabilitiesResponse advertises the encodings a stdio RPC server can
// decode and encode for method payloads.
type StdioRpcCapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encodings accepted for method request payloads and emitted for matching
	// response payloads.
	SupportedEncodings []PayloadEncoding `protobuf:"varint,1,rep,packed,name=supported_encodings,json=supportedEncodings,proto3,enum=recall.rpc.v1.PayloadEncoding" json:"supported_encodings,omitempty"`
	// Provider preference among supported_encodings. Recall may override this
	// preference for diagnostics when a supported encoding is explicitly needed.
	PreferredEncoding PayloadEncoding `protobuf:"varint,2,opt,name=preferred_encoding,json=preferredEncoding,proto3,enum=recall.rpc.v1.PayloadEncoding" json:"preferred_encoding,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StdioRpcCapabilitiesResponse) Reset() {
	*x = StdioRpcCapabilitiesResponse{}
	mi := &file_proto_recall_rpc_v1_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdioRpcCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdioRpcCapabilitiesResponse) ProtoMessage() {}

func (x *StdioRpcCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_rpc_v1_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdioRpcCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*StdioRpcCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_recall_rpc_v1_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *StdioRpcCapabilitiesResponse) GetSupportedEncodings() []PayloadEncoding {
	if x != nil {
		return x.SupportedEncodings
	}
	return nil
}

func (x *StdioRpcCapabilitiesResponse) GetPreferredEncoding() PayloadEncoding {
	if x != nil {
		return x.PreferredEncoding
	}
	return PayloadEncoding_PAYLOAD_ENCODING_UNSPECIFIED
}

var File_proto_recall_rpc_v1_rpc_proto protoreflect.FileDescriptor

const file_proto_recall_rpc_v1_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/recall/rpc/v1/rpc.proto\x12\rrecall.rpc.v1\"\x1d\n" +
	"\x1bStdioRpcCapabilitiesRequest\"\xbe\x01\n" +
	"\x1cStdioRpcCapabilitiesResponse\x12O\n" +
	"\x13supported_encodings\x18\x01 \x03(\x0e2\x1e.recall.rpc.v1.PayloadEncodingR\x12supportedEncodings\x12M\n" +
	"\x12preferred_encoding\x18\x02 \x01(\x0e2\x1e.recall.rpc.v1.PayloadEncodingR\x11preferredEncoding*\x82\x01\n" +
	"\x0fPayloadEncoding\x12 \n" +
	"\x1cPAYLOAD_ENCODING_UNSPECIFIED\x10\x00\x12$\n" +
	" PAYLOAD_ENCODING_PROTOBUF_BINARY\x10\x01\x12'\n" +
	"#PAYLOAD_ENCODING_PROTOBUF_TEXTPROTO\x10\x022}\n" +
	"\x0fStdioRpcControl\x12j\n" +
	"\x0fGetCapabilities\x12*.recall.rpc.v1.StdioRpcCapabilitiesRequest\x1a+.recall.rpc.v1.StdioRpcCapabilitiesResponseB\"Z recall/proto/recall/rpc/v1;rpcv1b\x06proto3"

var (
	file_proto_recall_rpc_v1_rpc_proto_rawDescOnce sync.Once
	file_proto_recall_rpc_v1_rpc_proto_rawDescData []byte
)

func file_proto_recall_rpc_v1_rpc_proto_rawDescGZIP() []byte {
	file_proto_recall_rpc_v1_rpc_proto_rawDescOnce.Do(func() {
		file_proto_recall_rpc_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recall_rpc_v1_rpc_proto_rawDesc), len(file_proto_recall_rpc_v1_rpc_proto_rawDesc)))
	})
	return file_proto_recall_rpc_v1_rpc_proto_rawDescData
}

var file_proto_recall_rpc_v1_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_recall_rpc_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_recall_rpc_v1_rpc_proto_goTypes = []any{
	(PayloadEncoding)(0),                 // 0: recall.rpc.v1.PayloadEncoding
	(*StdioRpcCapabilitiesRequest)(nil),  // 1: recall.rpc.v1.StdioRpcCapabilitiesRequest
	(*StdioRpcCapabilitiesResponse)(nil), // 2: recall.rpc.v1.StdioRpcCapabilitiesResponse
}
var file_proto_recall_rpc_v1_rpc_proto_depIdxs = []int32{
	0, // 0: recall.rpc.v1.StdioRpcCapabilitiesResponse.supported_encodings:type_name -> recall.rpc.v1.PayloadEncoding
	0, // 1: recall.rpc.v1.StdioRpcCapabilitiesResponse.preferred_encoding:type_name -> recall.rpc.v1.PayloadEncoding
	1, // 2: recall.rpc.v1.StdioRpcControl.GetCapabilities:input_type -> recall.rpc.v1.StdioRpcCapabilitiesRequest
	2, // 3: recall.rpc.v1.StdioRpcControl.GetCapabilities:output_type -> recall.rpc.v1.StdioRpcCapabilitiesResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_recall_rpc_v1_rpc_proto_init() }
func file_proto_recall_rpc_v1_rpc_proto_init() {
	if File_proto_recall_rpc_v1_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recall_rpc_v1_rpc_proto_rawDesc), len(file_proto_recall_rpc_v1_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recall_rpc_v1_rpc_proto_goTypes,
		DependencyIndexes: file_proto_recall_rpc_v1_rpc_proto_depIdxs,
		EnumInfos:         file_proto_recall_rpc_v1_rpc_proto_enumTypes,
		MessageInfos:      file_proto_recall_rpc_v1_rpc_proto_msgTypes,
	}.Build()
	File_proto_recall_rpc_v1_rpc_proto = out.File
	file_proto_recall_rpc_v1_rpc_proto_goTypes = nil
	file_proto_recall_rpc_v1_rpc_proto_depIdxs = nil
}
