// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/recall/search/v1/search.proto

package searchv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchRequest is the query payload sent by recall. Source routing and
// presentation controls remain recall-owned; selector hints are provider-local
// advisory inputs so expensive providers can skip unsupported or unrequested
// surfaces while recall still applies authoritative post-filtering.
type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider-native query text. Recall does not parse provider-specific query
	// operators after routing has selected a provider.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Optional soft maximum number of results the provider should return. When
	// absent or zero, the provider should return every reasonable match.
	Limit *uint32 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// Optional provider-local selectors or selector prefixes the caller is
	// interested in, such as file or file:content. Providers may use these as
	// optimization hints, but every returned result must still set a full
	// provider-local selector in object:match form.
	SelectorHints []string `protobuf:"bytes,3,rep,name=selector_hints,json=selectorHints,proto3" json:"selector_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *SearchRequest) GetSelectorHints() []string {
	if x != nil {
		return x.SelectorHints
	}
	return nil
}

// ListCapabilitiesRequest is empty because configured provider process args
// already select the local capability set.
type ListCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCapabilitiesRequest) Reset() {
	*x = ListCapabilitiesRequest{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapabilitiesRequest) ProtoMessage() {}

func (x *ListCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*ListCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{1}
}

// ListCapabilitiesResponse describes provider-local searchable surfaces.
type ListCapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider-local selectors, such as file:name or page:content. Recall prefixes
	// these selectors with the configured provider id when displaying full recall
	// selectors to operators.
	Surfaces      []*SearchSurface `protobuf:"bytes,1,rep,name=surfaces,proto3" json:"surfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCapabilitiesResponse) Reset() {
	*x = ListCapabilitiesResponse{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapabilitiesResponse) ProtoMessage() {}

func (x *ListCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*ListCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *ListCapabilitiesResponse) GetSurfaces() []*SearchSurface {
	if x != nil {
		return x.Surfaces
	}
	return nil
}

// SearchSurface describes one provider-local searchable surface advertised to
// operators. A surface is a capability, not a result; it tells recall which
// selectors may be useful before a query is run.
type SearchSurface struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full provider-local selector in recall's object:match taxonomy.
	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// Short human-facing label for list output. It is not used as a search result
	// title; result display data belongs in SearchResponse.Result.fields.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Concise explanation of what this selector searches.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSurface) Reset() {
	*x = SearchSurface{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSurface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSurface) ProtoMessage() {}

func (x *SearchSurface) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSurface.ProtoReflect.Descriptor instead.
func (*SearchSurface) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchSurface) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *SearchSurface) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchSurface) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// SearchResponse contains provider-local results and non-fatal diagnostics.
type SearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider-local results ordered best-first. Recall derives provider-local
	// rank from array position and then blends ranks across providers.
	Results []*SearchResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Non-fatal provider diagnostics. Warnings do not invalidate successful
	// results and are preserved for machine-readable output.
	Warnings      []*SearchResponse_Warning `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetResults() []*SearchResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetWarnings() []*SearchResponse_Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// OpenTarget describes one action or location a result or group can open.
type OpenTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*OpenTarget_Uri
	//	*OpenTarget_File
	Target        isOpenTarget_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTarget) Reset() {
	*x = OpenTarget{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTarget) ProtoMessage() {}

func (x *OpenTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTarget.ProtoReflect.Descriptor instead.
func (*OpenTarget) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *OpenTarget) GetTarget() isOpenTarget_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *OpenTarget) GetUri() *UriTarget {
	if x != nil {
		if x, ok := x.Target.(*OpenTarget_Uri); ok {
			return x.Uri
		}
	}
	return nil
}

func (x *OpenTarget) GetFile() *FileTarget {
	if x != nil {
		if x, ok := x.Target.(*OpenTarget_File); ok {
			return x.File
		}
	}
	return nil
}

type isOpenTarget_Target interface {
	isOpenTarget_Target()
}

type OpenTarget_Uri struct {
	Uri *UriTarget `protobuf:"bytes,1,opt,name=uri,proto3,oneof"`
}

type OpenTarget_File struct {
	File *FileTarget `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

func (*OpenTarget_Uri) isOpenTarget_Target() {}

func (*OpenTarget_File) isOpenTarget_Target() {}

// UriTarget is a generic URI-backed open target.
type UriTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URI to open. If the target needs source-specific coordinates such as a
	// message timestamp, encode them in this URI or permalink.
	Uri           string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UriTarget) Reset() {
	*x = UriTarget{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UriTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UriTarget) ProtoMessage() {}

func (x *UriTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UriTarget.ProtoReflect.Descriptor instead.
func (*UriTarget) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{6}
}

func (x *UriTarget) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

// FileTarget is a local file target with an optional 1-based open position.
type FileTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute local filesystem path.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Optional 1-based line within the file.
	Line *uint32 `protobuf:"varint,2,opt,name=line,proto3,oneof" json:"line,omitempty"`
	// Optional 1-based column within line. Requires line when present.
	Column        *uint32 `protobuf:"varint,3,opt,name=column,proto3,oneof" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTarget) Reset() {
	*x = FileTarget{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTarget) ProtoMessage() {}

func (x *FileTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTarget.ProtoReflect.Descriptor instead.
func (*FileTarget) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{7}
}

func (x *FileTarget) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileTarget) GetLine() uint32 {
	if x != nil && x.Line != nil {
		return *x.Line
	}
	return 0
}

func (x *FileTarget) GetColumn() uint32 {
	if x != nil && x.Column != nil {
		return *x.Column
	}
	return 0
}

// SearchGroup describes source-native grouping without provider-specific
// renderer code in recall.
type SearchGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable grouping key within the provider.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Human-readable group label.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Optional openable targets for the group. Group targets open the group
	// context, while result targets open individual results.
	Targets       []*OpenTarget `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGroup) Reset() {
	*x = SearchGroup{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGroup) ProtoMessage() {}

func (x *SearchGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGroup.ProtoReflect.Descriptor instead.
func (*SearchGroup) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{8}
}

func (x *SearchGroup) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SearchGroup) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchGroup) GetTargets() []*OpenTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

// Result is one provider-local search result. Required-by-contract fields are
// id, selector, and at least one field. Protobuf cannot express those
// constraints directly, so recall validates them after decoding.
type SearchResponse_Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider-stable identifier, unique within this provider. This is machine
	// identity, not display text; put user-visible identifiers such as Jira keys
	// or file paths into fields when they should render.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Full provider-local selector in recall's object:match taxonomy. This
	// should match one of the provider's advertised SearchSurface selectors when
	// the provider can list capabilities.
	Selector string `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	// Typed provider-owned facts about this result. Field keys must be unique
	// within a result and should be stable snake_case names. Recall renders
	// visible fields selected by format and preserves all fields in JSON.
	Fields []*SearchResponse_Result_Field `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	// Openable targets for this result, in provider-preferred order. The first
	// target is the primary terminal link when one exists; remaining targets may
	// be rendered as secondary actions.
	Targets []*OpenTarget `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	// Optional provider-preferred grouping identity. Grouping is source-native
	// data, such as a file, repository, channel, project, or parent page.
	Group *SearchGroup `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	// Optional provider-native score for diagnostics. Scores are not comparable
	// across providers and are not the primary blending signal.
	Score *float64 `protobuf:"fixed64,6,opt,name=score,proto3,oneof" json:"score,omitempty"`
	// Optional provider-suggested field layout for human rendering. Recall owns
	// final styling, separators, timestamp localization, and fallback behavior.
	Format        *SearchResponse_Result_Format `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse_Result) Reset() {
	*x = SearchResponse_Result{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse_Result) ProtoMessage() {}

func (x *SearchResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse_Result.ProtoReflect.Descriptor instead.
func (*SearchResponse_Result) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{4, 0}
}

func (x *SearchResponse_Result) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResponse_Result) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *SearchResponse_Result) GetFields() []*SearchResponse_Result_Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SearchResponse_Result) GetTargets() []*OpenTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *SearchResponse_Result) GetGroup() *SearchGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *SearchResponse_Result) GetScore() float64 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *SearchResponse_Result) GetFormat() *SearchResponse_Result_Format {
	if x != nil {
		return x.Format
	}
	return nil
}

// Warning describes non-fatal provider degradation.
type SearchResponse_Warning struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable diagnostic message.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Optional stable warning code for diagnostics and tests.
	Code          *string `protobuf:"bytes,2,opt,name=code,proto3,oneof" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse_Warning) Reset() {
	*x = SearchResponse_Warning{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse_Warning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse_Warning) ProtoMessage() {}

func (x *SearchResponse_Warning) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse_Warning.ProtoReflect.Descriptor instead.
func (*SearchResponse_Warning) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{4, 1}
}

func (x *SearchResponse_Warning) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchResponse_Warning) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

// Field is one typed result fact. It may be displayed in human output when
// visible and selected by Format, and is always preserved in JSON. Exactly
// one value kind must be set.
type SearchResponse_Result_Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable provider-owned field key, preferably snake_case. Examples include
	// path, line, column, snippet, ticket, summary, status, timestamp,
	// updated_at, author, repository, and url.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Hidden marks this field as machine-readable-only for normal human
	// rendering. Hidden fields are ignored by Format and fallback layout, but
	// remain available in JSON. Unset or false means the field is visible.
	Hidden *bool `protobuf:"varint,5,opt,name=hidden,proto3,oneof" json:"hidden,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*SearchResponse_Result_Field_Text
	//	*SearchResponse_Result_Field_Integer
	//	*SearchResponse_Result_Field_Timestamp
	Value         isSearchResponse_Result_Field_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse_Result_Field) Reset() {
	*x = SearchResponse_Result_Field{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse_Result_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse_Result_Field) ProtoMessage() {}

func (x *SearchResponse_Result_Field) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse_Result_Field.ProtoReflect.Descriptor instead.
func (*SearchResponse_Result_Field) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *SearchResponse_Result_Field) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SearchResponse_Result_Field) GetHidden() bool {
	if x != nil && x.Hidden != nil {
		return *x.Hidden
	}
	return false
}

func (x *SearchResponse_Result_Field) GetValue() isSearchResponse_Result_Field_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SearchResponse_Result_Field) GetText() string {
	if x != nil {
		if x, ok := x.Value.(*SearchResponse_Result_Field_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *SearchResponse_Result_Field) GetInteger() int64 {
	if x != nil {
		if x, ok := x.Value.(*SearchResponse_Result_Field_Integer); ok {
			return x.Integer
		}
	}
	return 0
}

func (x *SearchResponse_Result_Field) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Value.(*SearchResponse_Result_Field_Timestamp); ok {
			return x.Timestamp
		}
	}
	return nil
}

type isSearchResponse_Result_Field_Value interface {
	isSearchResponse_Result_Field_Value()
}

type SearchResponse_Result_Field_Text struct {
	// Provider-normalized text. Recall may collapse whitespace for terminal
	// rendering but preserves the original value in JSON.
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type SearchResponse_Result_Field_Integer struct {
	// Numeric fact, such as file line, file column, count, rank, priority, or
	// sequence number. Do not encode timestamps as integers; use timestamp.
	Integer int64 `protobuf:"varint,3,opt,name=integer,proto3,oneof"`
}

type SearchResponse_Result_Field_Timestamp struct {
	// Source-domain instant. Providers should populate UTC instants; recall
	// renders human output in the operator's local timezone without showing
	// a timezone suffix.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3,oneof"`
}

func (*SearchResponse_Result_Field_Text) isSearchResponse_Result_Field_Value() {}

func (*SearchResponse_Result_Field_Integer) isSearchResponse_Result_Field_Value() {}

func (*SearchResponse_Result_Field_Timestamp) isSearchResponse_Result_Field_Value() {}

// Format is a provider suggestion for generic human rendering. It references
// Field.key values and does not declare which fields exist. Hidden, unknown,
// or missing keys are skipped. Duplicate keys are ignored after their first
// occurrence. Fields not rendered here remain available in JSON.
type SearchResponse_Result_Format struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field keys that form the primary result line. If empty or if all keys
	// are hidden or missing, recall falls back to the first visible field.
	TitleFields []string `protobuf:"bytes,1,rep,name=title_fields,json=titleFields,proto3" json:"title_fields,omitempty"`
	// Field keys rendered as ordered detail rows after the title. If empty,
	// recall may render visible fields not used in the title as details.
	DetailFields  []string `protobuf:"bytes,2,rep,name=detail_fields,json=detailFields,proto3" json:"detail_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse_Result_Format) Reset() {
	*x = SearchResponse_Result_Format{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse_Result_Format) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse_Result_Format) ProtoMessage() {}

func (x *SearchResponse_Result_Format) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse_Result_Format.ProtoReflect.Descriptor instead.
func (*SearchResponse_Result_Format) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{4, 0, 1}
}

func (x *SearchResponse_Result_Format) GetTitleFields() []string {
	if x != nil {
		return x.TitleFields
	}
	return nil
}

func (x *SearchResponse_Result_Format) GetDetailFields() []string {
	if x != nil {
		return x.DetailFields
	}
	return nil
}

var File_proto_recall_search_v1_search_proto protoreflect.FileDescriptor

const file_proto_recall_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"#proto/recall/search/v1/search.proto\x12\x10recall.search.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"q\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\rH\x00R\x05limit\x88\x01\x01\x12%\n" +
	"\x0eselector_hints\x18\x03 \x03(\tR\rselectorHintsB\b\n" +
	"\x06_limit\"\x19\n" +
	"\x17ListCapabilitiesRequest\"W\n" +
	"\x18ListCapabilitiesResponse\x12;\n" +
	"\bsurfaces\x18\x01 \x03(\v2\x1f.recall.search.v1.SearchSurfaceR\bsurfaces\"c\n" +
	"\rSearchSurface\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xc5\x06\n" +
	"\x0eSearchResponse\x12A\n" +
	"\aresults\x18\x01 \x03(\v2'.recall.search.v1.SearchResponse.ResultR\aresults\x12D\n" +
	"\bwarnings\x18\x02 \x03(\v2(.recall.search.v1.SearchResponse.WarningR\bwarnings\x1a\xe2\x04\n" +
	"\x06Result\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12E\n" +
	"\x06fields\x18\x03 \x03(\v2-.recall.search.v1.SearchResponse.Result.FieldR\x06fields\x126\n" +
	"\atargets\x18\x04 \x03(\v2\x1c.recall.search.v1.OpenTargetR\atargets\x123\n" +
	"\x05group\x18\x05 \x01(\v2\x1d.recall.search.v1.SearchGroupR\x05group\x12\x19\n" +
	"\x05score\x18\x06 \x01(\x01H\x00R\x05score\x88\x01\x01\x12F\n" +
	"\x06format\x18\a \x01(\v2..recall.search.v1.SearchResponse.Result.FormatR\x06format\x1a\xb8\x01\n" +
	"\x05Field\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\x06hidden\x18\x05 \x01(\bH\x01R\x06hidden\x88\x01\x01\x12\x14\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x12\x1a\n" +
	"\ainteger\x18\x03 \x01(\x03H\x00R\ainteger\x12:\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\ttimestampB\a\n" +
	"\x05valueB\t\n" +
	"\a_hidden\x1aP\n" +
	"\x06Format\x12!\n" +
	"\ftitle_fields\x18\x01 \x03(\tR\vtitleFields\x12#\n" +
	"\rdetail_fields\x18\x02 \x03(\tR\fdetailFieldsB\b\n" +
	"\x06_score\x1aE\n" +
	"\aWarning\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x17\n" +
	"\x04code\x18\x02 \x01(\tH\x00R\x04code\x88\x01\x01B\a\n" +
	"\x05_code\"{\n" +
	"\n" +
	"OpenTarget\x12/\n" +
	"\x03uri\x18\x01 \x01(\v2\x1b.recall.search.v1.UriTargetH\x00R\x03uri\x122\n" +
	"\x04file\x18\x02 \x01(\v2\x1c.recall.search.v1.FileTargetH\x00R\x04fileB\b\n" +
	"\x06target\"\x1d\n" +
	"\tUriTarget\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"j\n" +
	"\n" +
	"FileTarget\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x17\n" +
	"\x04line\x18\x02 \x01(\rH\x00R\x04line\x88\x01\x01\x12\x1b\n" +
	"\x06column\x18\x03 \x01(\rH\x01R\x06column\x88\x01\x01B\a\n" +
	"\x05_lineB\t\n" +
	"\a_column\"m\n" +
	"\vSearchGroup\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x126\n" +
	"\atargets\x18\x03 \x03(\v2\x1c.recall.search.v1.OpenTargetR\atargets2\xc8\x01\n" +
	"\x0eSearchProvider\x12K\n" +
	"\x06Search\x12\x1f.recall.search.v1.SearchRequest\x1a .recall.search.v1.SearchResponse\x12i\n" +
	"\x10ListCapabilities\x12).recall.search.v1.ListCapabilitiesRequest\x1a*.recall.search.v1.ListCapabilitiesResponseB;Z9github.com/solodov/recall/proto/recall/search/v1;searchv1b\x06proto3"

var (
	file_proto_recall_search_v1_search_proto_rawDescOnce sync.Once
	file_proto_recall_search_v1_search_proto_rawDescData []byte
)

func file_proto_recall_search_v1_search_proto_rawDescGZIP() []byte {
	file_proto_recall_search_v1_search_proto_rawDescOnce.Do(func() {
		file_proto_recall_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recall_search_v1_search_proto_rawDesc), len(file_proto_recall_search_v1_search_proto_rawDesc)))
	})
	return file_proto_recall_search_v1_search_proto_rawDescData
}

var file_proto_recall_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_recall_search_v1_search_proto_goTypes = []any{
	(*SearchRequest)(nil),                // 0: recall.search.v1.SearchRequest
	(*ListCapabilitiesRequest)(nil),      // 1: recall.search.v1.ListCapabilitiesRequest
	(*ListCapabilitiesResponse)(nil),     // 2: recall.search.v1.ListCapabilitiesResponse
	(*SearchSurface)(nil),                // 3: recall.search.v1.SearchSurface
	(*SearchResponse)(nil),               // 4: recall.search.v1.SearchResponse
	(*OpenTarget)(nil),                   // 5: recall.search.v1.OpenTarget
	(*UriTarget)(nil),                    // 6: recall.search.v1.UriTarget
	(*FileTarget)(nil),                   // 7: recall.search.v1.FileTarget
	(*SearchGroup)(nil),                  // 8: recall.search.v1.SearchGroup
	(*SearchResponse_Result)(nil),        // 9: recall.search.v1.SearchResponse.Result
	(*SearchResponse_Warning)(nil),       // 10: recall.search.v1.SearchResponse.Warning
	(*SearchResponse_Result_Field)(nil),  // 11: recall.search.v1.SearchResponse.Result.Field
	(*SearchResponse_Result_Format)(nil), // 12: recall.search.v1.SearchResponse.Result.Format
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
}
var file_proto_recall_search_v1_search_proto_depIdxs = []int32{
	3,  // 0: recall.search.v1.ListCapabilitiesResponse.surfaces:type_name -> recall.search.v1.SearchSurface
	9,  // 1: recall.search.v1.SearchResponse.results:type_name -> recall.search.v1.SearchResponse.Result
	10, // 2: recall.search.v1.SearchResponse.warnings:type_name -> recall.search.v1.SearchResponse.Warning
	6,  // 3: recall.search.v1.OpenTarget.uri:type_name -> recall.search.v1.UriTarget
	7,  // 4: recall.search.v1.OpenTarget.file:type_name -> recall.search.v1.FileTarget
	5,  // 5: recall.search.v1.SearchGroup.targets:type_name -> recall.search.v1.OpenTarget
	11, // 6: recall.search.v1.SearchResponse.Result.fields:type_name -> recall.search.v1.SearchResponse.Result.Field
	5,  // 7: recall.search.v1.SearchResponse.Result.targets:type_name -> recall.search.v1.OpenTarget
	8,  // 8: recall.search.v1.SearchResponse.Result.group:type_name -> recall.search.v1.SearchGroup
	12, // 9: recall.search.v1.SearchResponse.Result.format:type_name -> recall.search.v1.SearchResponse.Result.Format
	13, // 10: recall.search.v1.SearchResponse.Result.Field.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 11: recall.search.v1.SearchProvider.Search:input_type -> recall.search.v1.SearchRequest
	1,  // 12: recall.search.v1.SearchProvider.ListCapabilities:input_type -> recall.search.v1.ListCapabilitiesRequest
	4,  // 13: recall.search.v1.SearchProvider.Search:output_type -> recall.search.v1.SearchResponse
	2,  // 14: recall.search.v1.SearchProvider.ListCapabilities:output_type -> recall.search.v1.ListCapabilitiesResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_recall_search_v1_search_proto_init() }
func file_proto_recall_search_v1_search_proto_init() {
	if File_proto_recall_search_v1_search_proto != nil {
		return
	}
	file_proto_recall_search_v1_search_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_recall_search_v1_search_proto_msgTypes[5].OneofWrappers = []any{
		(*OpenTarget_Uri)(nil),
		(*OpenTarget_File)(nil),
	}
	file_proto_recall_search_v1_search_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_recall_search_v1_search_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_recall_search_v1_search_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_recall_search_v1_search_proto_msgTypes[11].OneofWrappers = []any{
		(*SearchResponse_Result_Field_Text)(nil),
		(*SearchResponse_Result_Field_Integer)(nil),
		(*SearchResponse_Result_Field_Timestamp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recall_search_v1_search_proto_rawDesc), len(file_proto_recall_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recall_search_v1_search_proto_goTypes,
		DependencyIndexes: file_proto_recall_search_v1_search_proto_depIdxs,
		MessageInfos:      file_proto_recall_search_v1_search_proto_msgTypes,
	}.Build()
	File_proto_recall_search_v1_search_proto = out.File
	file_proto_recall_search_v1_search_proto_goTypes = nil
	file_proto_recall_search_v1_search_proto_depIdxs = nil
}
