// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/recall/search/v1/search.proto

package searchv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchRequest is the query payload sent by recall. Recall-level routing and
// presentation flags are handled by recall and are not serialized here.
type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider-native query text.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Soft maximum number of hits the provider should return.
	Limit         uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SearchResponse contains provider-local results and non-fatal diagnostics.
type SearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recall derives provider-local rank from array position.
	Hits []*SearchHit `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	// Non-fatal provider diagnostics.
	Warnings      []*Warning `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// SearchHit is one provider-local search result.
type SearchHit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider-stable identifier, unique within this provider.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Coarse result type, such as org_entry, note, email, event, or command.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Primary display label for the result.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Optional provider-generated context or matched text.
	Snippet *string `protobuf:"bytes,4,opt,name=snippet,proto3,oneof" json:"snippet,omitempty"`
	// Optional provider-native score for diagnostics. Scores are not comparable
	// across providers and are not the primary blending signal.
	Score *float64 `protobuf:"fixed64,5,opt,name=score,proto3,oneof" json:"score,omitempty"`
	// Named actions or locations. The first URI is the primary action.
	Uris []*NamedUri `protobuf:"bytes,6,rep,name=uris,proto3" json:"uris,omitempty"`
	// Optional provider-preferred grouping identity.
	Group *SearchGroup `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`
	// Optional source-domain time useful for scanning the result, such as email
	// sent time, calendar start time, or shell command execution time.
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchHit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchHit) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SearchHit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchHit) GetSnippet() string {
	if x != nil && x.Snippet != nil {
		return *x.Snippet
	}
	return ""
}

func (x *SearchHit) GetScore() float64 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *SearchHit) GetUris() []*NamedUri {
	if x != nil {
		return x.Uris
	}
	return nil
}

func (x *SearchHit) GetGroup() *SearchGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *SearchHit) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// NamedUri is the only action abstraction in the search contract.
type NamedUri struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable action label, such as open, file, thread, event, web, or source.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// URI to open or expose for the named action.
	Uri           string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedUri) Reset() {
	*x = NamedUri{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedUri) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedUri) ProtoMessage() {}

func (x *NamedUri) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedUri.ProtoReflect.Descriptor instead.
func (*NamedUri) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *NamedUri) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamedUri) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

// SearchGroup describes source-native grouping without provider-specific
// renderer code in recall.
type SearchGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable grouping key within the provider.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Human-readable group label.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Optional named actions or locations for the group.
	Uris          []*NamedUri `protobuf:"bytes,3,rep,name=uris,proto3" json:"uris,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGroup) Reset() {
	*x = SearchGroup{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGroup) ProtoMessage() {}

func (x *SearchGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGroup.ProtoReflect.Descriptor instead.
func (*SearchGroup) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchGroup) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SearchGroup) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchGroup) GetUris() []*NamedUri {
	if x != nil {
		return x.Uris
	}
	return nil
}

// Warning describes non-fatal provider degradation.
type Warning struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable diagnostic message.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Optional stable warning code for diagnostics and tests.
	Code          *string `protobuf:"bytes,2,opt,name=code,proto3,oneof" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warning) Reset() {
	*x = Warning{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warning) ProtoMessage() {}

func (x *Warning) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warning.ProtoReflect.Descriptor instead.
func (*Warning) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *Warning) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Warning) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

var File_proto_recall_search_v1_search_proto protoreflect.FileDescriptor

const file_proto_recall_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"#proto/recall/search/v1/search.proto\x12\x10recall.search.v1\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"x\n" +
	"\x0eSearchResponse\x12/\n" +
	"\x04hits\x18\x01 \x03(\v2\x1b.recall.search.v1.SearchHitR\x04hits\x125\n" +
	"\bwarnings\x18\x02 \x03(\v2\x19.recall.search.v1.WarningR\bwarnings\"\xb7\x02\n" +
	"\tSearchHit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1d\n" +
	"\asnippet\x18\x04 \x01(\tH\x00R\asnippet\x88\x01\x01\x12\x19\n" +
	"\x05score\x18\x05 \x01(\x01H\x01R\x05score\x88\x01\x01\x12.\n" +
	"\x04uris\x18\x06 \x03(\v2\x1a.recall.search.v1.NamedUriR\x04uris\x123\n" +
	"\x05group\x18\a \x01(\v2\x1d.recall.search.v1.SearchGroupR\x05group\x12;\n" +
	"\voccurred_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAtB\n" +
	"\n" +
	"\b_snippetB\b\n" +
	"\x06_score\"0\n" +
	"\bNamedUri\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\"e\n" +
	"\vSearchGroup\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12.\n" +
	"\x04uris\x18\x03 \x03(\v2\x1a.recall.search.v1.NamedUriR\x04uris\"E\n" +
	"\aWarning\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x17\n" +
	"\x04code\x18\x02 \x01(\tH\x00R\x04code\x88\x01\x01B\a\n" +
	"\x05_code2]\n" +
	"\x0eSearchProvider\x12K\n" +
	"\x06Search\x12\x1f.recall.search.v1.SearchRequest\x1a .recall.search.v1.SearchResponseB(Z&recall/proto/recall/search/v1;searchv1b\x06proto3"

var (
	file_proto_recall_search_v1_search_proto_rawDescOnce sync.Once
	file_proto_recall_search_v1_search_proto_rawDescData []byte
)

func file_proto_recall_search_v1_search_proto_rawDescGZIP() []byte {
	file_proto_recall_search_v1_search_proto_rawDescOnce.Do(func() {
		file_proto_recall_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recall_search_v1_search_proto_rawDesc), len(file_proto_recall_search_v1_search_proto_rawDesc)))
	})
	return file_proto_recall_search_v1_search_proto_rawDescData
}

var file_proto_recall_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_recall_search_v1_search_proto_goTypes = []any{
	(*SearchRequest)(nil),         // 0: recall.search.v1.SearchRequest
	(*SearchResponse)(nil),        // 1: recall.search.v1.SearchResponse
	(*SearchHit)(nil),             // 2: recall.search.v1.SearchHit
	(*NamedUri)(nil),              // 3: recall.search.v1.NamedUri
	(*SearchGroup)(nil),           // 4: recall.search.v1.SearchGroup
	(*Warning)(nil),               // 5: recall.search.v1.Warning
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_recall_search_v1_search_proto_depIdxs = []int32{
	2, // 0: recall.search.v1.SearchResponse.hits:type_name -> recall.search.v1.SearchHit
	5, // 1: recall.search.v1.SearchResponse.warnings:type_name -> recall.search.v1.Warning
	3, // 2: recall.search.v1.SearchHit.uris:type_name -> recall.search.v1.NamedUri
	4, // 3: recall.search.v1.SearchHit.group:type_name -> recall.search.v1.SearchGroup
	6, // 4: recall.search.v1.SearchHit.occurred_at:type_name -> google.protobuf.Timestamp
	3, // 5: recall.search.v1.SearchGroup.uris:type_name -> recall.search.v1.NamedUri
	0, // 6: recall.search.v1.SearchProvider.Search:input_type -> recall.search.v1.SearchRequest
	1, // 7: recall.search.v1.SearchProvider.Search:output_type -> recall.search.v1.SearchResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_recall_search_v1_search_proto_init() }
func file_proto_recall_search_v1_search_proto_init() {
	if File_proto_recall_search_v1_search_proto != nil {
		return
	}
	file_proto_recall_search_v1_search_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_recall_search_v1_search_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recall_search_v1_search_proto_rawDesc), len(file_proto_recall_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recall_search_v1_search_proto_goTypes,
		DependencyIndexes: file_proto_recall_search_v1_search_proto_depIdxs,
		MessageInfos:      file_proto_recall_search_v1_search_proto_msgTypes,
	}.Build()
	File_proto_recall_search_v1_search_proto = out.File
	file_proto_recall_search_v1_search_proto_goTypes = nil
	file_proto_recall_search_v1_search_proto_depIdxs = nil
}
