// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/recall/search/v1/search.proto

package searchv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchRequest is the query payload sent by recall. Source routing and
// presentation controls remain recall-owned; selector hints are advisory so
// expensive providers can skip unsupported or unrequested result families while
// recall still applies authoritative post-filtering.
type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider-native query text.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Optional soft maximum number of hits the provider should return. When
	// absent, the provider should return every reasonable match.
	Limit *uint32 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// Optional provider-local selectors the caller is interested in, such as
	// file:content. Providers may use these as optimization hints, but must still
	// return valid provider-native selectors on hits.
	SelectorHints []string `protobuf:"bytes,3,rep,name=selector_hints,json=selectorHints,proto3" json:"selector_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *SearchRequest) GetSelectorHints() []string {
	if x != nil {
		return x.SelectorHints
	}
	return nil
}

// ListCapabilitiesRequest is empty because configured provider process args
// already select the local capability set.
type ListCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCapabilitiesRequest) Reset() {
	*x = ListCapabilitiesRequest{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapabilitiesRequest) ProtoMessage() {}

func (x *ListCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*ListCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{1}
}

// ListCapabilitiesResponse describes provider-local searchable surfaces.
type ListCapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider-local selectors, such as file:name or page:content.
	Surfaces      []*SearchSurface `protobuf:"bytes,1,rep,name=surfaces,proto3" json:"surfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCapabilitiesResponse) Reset() {
	*x = ListCapabilitiesResponse{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapabilitiesResponse) ProtoMessage() {}

func (x *ListCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*ListCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *ListCapabilitiesResponse) GetSurfaces() []*SearchSurface {
	if x != nil {
		return x.Surfaces
	}
	return nil
}

// SearchSurface describes one provider-local selector advertised to operators.
type SearchSurface struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider-local selector in recall's object:match taxonomy.
	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// Short human-facing label for list output.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Concise explanation of what this selector searches.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSurface) Reset() {
	*x = SearchSurface{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSurface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSurface) ProtoMessage() {}

func (x *SearchSurface) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSurface.ProtoReflect.Descriptor instead.
func (*SearchSurface) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchSurface) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *SearchSurface) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchSurface) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// SearchResponse contains provider-local results and non-fatal diagnostics.
type SearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recall derives provider-local rank from array position.
	Hits []*SearchHit `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	// Non-fatal provider diagnostics.
	Warnings      []*Warning `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// SearchHit is one provider-local search result.
type SearchHit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider-stable identifier, unique within this provider.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Provider-local selector in recall's object:match taxonomy.
	Selector string `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	// Primary display label for the result.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Optional provider-generated context or matched text.
	Snippet *string `protobuf:"bytes,4,opt,name=snippet,proto3,oneof" json:"snippet,omitempty"`
	// Optional provider-native score for diagnostics. Scores are not comparable
	// across providers and are not the primary blending signal.
	Score *float64 `protobuf:"fixed64,5,opt,name=score,proto3,oneof" json:"score,omitempty"`
	// Openable targets for this result, in provider-preferred order.
	Targets []*OpenTarget `protobuf:"bytes,6,rep,name=targets,proto3" json:"targets,omitempty"`
	// Optional provider-preferred grouping identity.
	Group *SearchGroup `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`
	// Optional source-domain time useful for scanning the result, such as email
	// sent time, calendar start time, or shell command execution time.
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *SearchHit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchHit) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *SearchHit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchHit) GetSnippet() string {
	if x != nil && x.Snippet != nil {
		return *x.Snippet
	}
	return ""
}

func (x *SearchHit) GetScore() float64 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *SearchHit) GetTargets() []*OpenTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *SearchHit) GetGroup() *SearchGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *SearchHit) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// OpenTarget describes one action or location a result can open.
type OpenTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*OpenTarget_Uri
	//	*OpenTarget_File
	Target        isOpenTarget_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTarget) Reset() {
	*x = OpenTarget{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTarget) ProtoMessage() {}

func (x *OpenTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTarget.ProtoReflect.Descriptor instead.
func (*OpenTarget) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{6}
}

func (x *OpenTarget) GetTarget() isOpenTarget_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *OpenTarget) GetUri() *UriTarget {
	if x != nil {
		if x, ok := x.Target.(*OpenTarget_Uri); ok {
			return x.Uri
		}
	}
	return nil
}

func (x *OpenTarget) GetFile() *FileTarget {
	if x != nil {
		if x, ok := x.Target.(*OpenTarget_File); ok {
			return x.File
		}
	}
	return nil
}

type isOpenTarget_Target interface {
	isOpenTarget_Target()
}

type OpenTarget_Uri struct {
	Uri *UriTarget `protobuf:"bytes,1,opt,name=uri,proto3,oneof"`
}

type OpenTarget_File struct {
	File *FileTarget `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

func (*OpenTarget_Uri) isOpenTarget_Target() {}

func (*OpenTarget_File) isOpenTarget_Target() {}

// UriTarget is a generic URI-backed open target.
type UriTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URI to open.
	Uri           string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UriTarget) Reset() {
	*x = UriTarget{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UriTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UriTarget) ProtoMessage() {}

func (x *UriTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UriTarget.ProtoReflect.Descriptor instead.
func (*UriTarget) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{7}
}

func (x *UriTarget) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

// FileTarget is a local file target with an optional 1-based position.
type FileTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute local filesystem path.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Optional 1-based line within the file.
	Line *uint32 `protobuf:"varint,2,opt,name=line,proto3,oneof" json:"line,omitempty"`
	// Optional 1-based column within line. Requires line when present.
	Column        *uint32 `protobuf:"varint,3,opt,name=column,proto3,oneof" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTarget) Reset() {
	*x = FileTarget{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTarget) ProtoMessage() {}

func (x *FileTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTarget.ProtoReflect.Descriptor instead.
func (*FileTarget) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{8}
}

func (x *FileTarget) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileTarget) GetLine() uint32 {
	if x != nil && x.Line != nil {
		return *x.Line
	}
	return 0
}

func (x *FileTarget) GetColumn() uint32 {
	if x != nil && x.Column != nil {
		return *x.Column
	}
	return 0
}

// SearchGroup describes source-native grouping without provider-specific
// renderer code in recall.
type SearchGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable grouping key within the provider.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Human-readable group label.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Optional openable targets for the group.
	Targets       []*OpenTarget `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGroup) Reset() {
	*x = SearchGroup{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGroup) ProtoMessage() {}

func (x *SearchGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGroup.ProtoReflect.Descriptor instead.
func (*SearchGroup) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{9}
}

func (x *SearchGroup) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SearchGroup) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchGroup) GetTargets() []*OpenTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

// Warning describes non-fatal provider degradation.
type Warning struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable diagnostic message.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Optional stable warning code for diagnostics and tests.
	Code          *string `protobuf:"bytes,2,opt,name=code,proto3,oneof" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warning) Reset() {
	*x = Warning{}
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warning) ProtoMessage() {}

func (x *Warning) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recall_search_v1_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warning.ProtoReflect.Descriptor instead.
func (*Warning) Descriptor() ([]byte, []int) {
	return file_proto_recall_search_v1_search_proto_rawDescGZIP(), []int{10}
}

func (x *Warning) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Warning) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

var File_proto_recall_search_v1_search_proto protoreflect.FileDescriptor

const file_proto_recall_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"#proto/recall/search/v1/search.proto\x12\x10recall.search.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"q\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\rH\x00R\x05limit\x88\x01\x01\x12%\n" +
	"\x0eselector_hints\x18\x03 \x03(\tR\rselectorHintsB\b\n" +
	"\x06_limit\"\x19\n" +
	"\x17ListCapabilitiesRequest\"W\n" +
	"\x18ListCapabilitiesResponse\x12;\n" +
	"\bsurfaces\x18\x01 \x03(\v2\x1f.recall.search.v1.SearchSurfaceR\bsurfaces\"c\n" +
	"\rSearchSurface\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"x\n" +
	"\x0eSearchResponse\x12/\n" +
	"\x04hits\x18\x01 \x03(\v2\x1b.recall.search.v1.SearchHitR\x04hits\x125\n" +
	"\bwarnings\x18\x02 \x03(\v2\x19.recall.search.v1.WarningR\bwarnings\"\xc7\x02\n" +
	"\tSearchHit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1d\n" +
	"\asnippet\x18\x04 \x01(\tH\x00R\asnippet\x88\x01\x01\x12\x19\n" +
	"\x05score\x18\x05 \x01(\x01H\x01R\x05score\x88\x01\x01\x126\n" +
	"\atargets\x18\x06 \x03(\v2\x1c.recall.search.v1.OpenTargetR\atargets\x123\n" +
	"\x05group\x18\a \x01(\v2\x1d.recall.search.v1.SearchGroupR\x05group\x12;\n" +
	"\voccurred_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAtB\n" +
	"\n" +
	"\b_snippetB\b\n" +
	"\x06_score\"{\n" +
	"\n" +
	"OpenTarget\x12/\n" +
	"\x03uri\x18\x01 \x01(\v2\x1b.recall.search.v1.UriTargetH\x00R\x03uri\x122\n" +
	"\x04file\x18\x02 \x01(\v2\x1c.recall.search.v1.FileTargetH\x00R\x04fileB\b\n" +
	"\x06target\"\x1d\n" +
	"\tUriTarget\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"j\n" +
	"\n" +
	"FileTarget\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x17\n" +
	"\x04line\x18\x02 \x01(\rH\x00R\x04line\x88\x01\x01\x12\x1b\n" +
	"\x06column\x18\x03 \x01(\rH\x01R\x06column\x88\x01\x01B\a\n" +
	"\x05_lineB\t\n" +
	"\a_column\"m\n" +
	"\vSearchGroup\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x126\n" +
	"\atargets\x18\x03 \x03(\v2\x1c.recall.search.v1.OpenTargetR\atargets\"E\n" +
	"\aWarning\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x17\n" +
	"\x04code\x18\x02 \x01(\tH\x00R\x04code\x88\x01\x01B\a\n" +
	"\x05_code2\xc8\x01\n" +
	"\x0eSearchProvider\x12K\n" +
	"\x06Search\x12\x1f.recall.search.v1.SearchRequest\x1a .recall.search.v1.SearchResponse\x12i\n" +
	"\x10ListCapabilities\x12).recall.search.v1.ListCapabilitiesRequest\x1a*.recall.search.v1.ListCapabilitiesResponseB;Z9github.com/solodov/recall/proto/recall/search/v1;searchv1b\x06proto3"

var (
	file_proto_recall_search_v1_search_proto_rawDescOnce sync.Once
	file_proto_recall_search_v1_search_proto_rawDescData []byte
)

func file_proto_recall_search_v1_search_proto_rawDescGZIP() []byte {
	file_proto_recall_search_v1_search_proto_rawDescOnce.Do(func() {
		file_proto_recall_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recall_search_v1_search_proto_rawDesc), len(file_proto_recall_search_v1_search_proto_rawDesc)))
	})
	return file_proto_recall_search_v1_search_proto_rawDescData
}

var file_proto_recall_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_recall_search_v1_search_proto_goTypes = []any{
	(*SearchRequest)(nil),            // 0: recall.search.v1.SearchRequest
	(*ListCapabilitiesRequest)(nil),  // 1: recall.search.v1.ListCapabilitiesRequest
	(*ListCapabilitiesResponse)(nil), // 2: recall.search.v1.ListCapabilitiesResponse
	(*SearchSurface)(nil),            // 3: recall.search.v1.SearchSurface
	(*SearchResponse)(nil),           // 4: recall.search.v1.SearchResponse
	(*SearchHit)(nil),                // 5: recall.search.v1.SearchHit
	(*OpenTarget)(nil),               // 6: recall.search.v1.OpenTarget
	(*UriTarget)(nil),                // 7: recall.search.v1.UriTarget
	(*FileTarget)(nil),               // 8: recall.search.v1.FileTarget
	(*SearchGroup)(nil),              // 9: recall.search.v1.SearchGroup
	(*Warning)(nil),                  // 10: recall.search.v1.Warning
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_proto_recall_search_v1_search_proto_depIdxs = []int32{
	3,  // 0: recall.search.v1.ListCapabilitiesResponse.surfaces:type_name -> recall.search.v1.SearchSurface
	5,  // 1: recall.search.v1.SearchResponse.hits:type_name -> recall.search.v1.SearchHit
	10, // 2: recall.search.v1.SearchResponse.warnings:type_name -> recall.search.v1.Warning
	6,  // 3: recall.search.v1.SearchHit.targets:type_name -> recall.search.v1.OpenTarget
	9,  // 4: recall.search.v1.SearchHit.group:type_name -> recall.search.v1.SearchGroup
	11, // 5: recall.search.v1.SearchHit.occurred_at:type_name -> google.protobuf.Timestamp
	7,  // 6: recall.search.v1.OpenTarget.uri:type_name -> recall.search.v1.UriTarget
	8,  // 7: recall.search.v1.OpenTarget.file:type_name -> recall.search.v1.FileTarget
	6,  // 8: recall.search.v1.SearchGroup.targets:type_name -> recall.search.v1.OpenTarget
	0,  // 9: recall.search.v1.SearchProvider.Search:input_type -> recall.search.v1.SearchRequest
	1,  // 10: recall.search.v1.SearchProvider.ListCapabilities:input_type -> recall.search.v1.ListCapabilitiesRequest
	4,  // 11: recall.search.v1.SearchProvider.Search:output_type -> recall.search.v1.SearchResponse
	2,  // 12: recall.search.v1.SearchProvider.ListCapabilities:output_type -> recall.search.v1.ListCapabilitiesResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_recall_search_v1_search_proto_init() }
func file_proto_recall_search_v1_search_proto_init() {
	if File_proto_recall_search_v1_search_proto != nil {
		return
	}
	file_proto_recall_search_v1_search_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_recall_search_v1_search_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_recall_search_v1_search_proto_msgTypes[6].OneofWrappers = []any{
		(*OpenTarget_Uri)(nil),
		(*OpenTarget_File)(nil),
	}
	file_proto_recall_search_v1_search_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_recall_search_v1_search_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recall_search_v1_search_proto_rawDesc), len(file_proto_recall_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recall_search_v1_search_proto_goTypes,
		DependencyIndexes: file_proto_recall_search_v1_search_proto_depIdxs,
		MessageInfos:      file_proto_recall_search_v1_search_proto_msgTypes,
	}.Build()
	File_proto_recall_search_v1_search_proto = out.File
	file_proto_recall_search_v1_search_proto_goTypes = nil
	file_proto_recall_search_v1_search_proto_depIdxs = nil
}
